//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hydra2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sample
    {
        public int Id { get; set; }
        public int Id_Station { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<float> Level { get; set; }
        public Nullable<float> Flow { get; set; }
        public Nullable<float> Temperature { get; set; }
    
        public virtual Station Station { get; set; }
    }
}
