//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hydra2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Station()
        {
            this.Sample = new HashSet<Sample>();
        }
    
        public int Id { get; set; }
        public string Spot { get; set; }
        public int Spa_val { get; set; }
        public Nullable<float> Spa0 { get; set; }
        public Nullable<float> Spa1 { get; set; }
        public Nullable<float> Spa2 { get; set; }
        public Nullable<float> Spa3 { get; set; }
        public Nullable<float> Spa3e { get; set; }
        public int Type { get; set; }
        public string Link { get; set; }
        public int Id_River { get; set; }
        public int DownLoadType { get; set; }
    
        public virtual River River { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sample> Sample { get; set; }
    }
}
